//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimOther
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeClaimId { get; set; }
        public string Details { get; set; }
    
        public virtual EmployeeClaim EmployeeClaim { get; set; }
    }
}
